version: "3"

services:
  database:
    image: postgres:12
    expose:
      - 5432
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "-c timezone=UTC"
    ports:
      - "5432:5432"
    restart: always

networks:
  NETWORK:
    external: true
